### ISSUE TITLE
Blank error message in MS Edge browser

### ISSUE THREAD

**Issue by KajetanMischok** [kaltura/mwEmbed#3076] opened 2016-10-20 07:53 UTC
We are facing a very strange error in Windows Edge browser. If we play videos with VAST midroll ads integrated the player will crash with an empty error message.
![kaltura-error](https://cloud.githubusercontent.com/assets/5823059/19550559/4d74ad9e-96aa-11e6-8292-599f0631cd9f.jpg)

Sometimes the video will play till the end, but without showing the ads. We are using VPAAS version of kaltura. And in IE, Chrome and firefox everything is working as expected. You can take a look at the issue on studyflix.de.

We are trying to find a solution for almost one week. But due to the blank error message we are out of ideas on how to fix it.

We would highly appreciate every hint on how we can get the course of the error. If i can provide any further information, please leave me am comment.

We are using the kWidget HTML5 Version 2.48.2.

**Comment by kaltura-hooks** [comment] 2016-10-20 08:00
Hi @KajetanMischok,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment] 2017-09-01 15:10
@KajetanMischok I couldn't reproduce the issue with the error message.
What I see when the ad doesn't play is that you have an event listener, that should replace the random string with a qualified string that an ad server can respond to with an ad, and it doesn't replace it for whatever reason.

**Comment by MischokNG** [comment] 2017-09-02 08:52
@OrenMe Thank you very much for your advice. I think the issue was solved by some other refactoring. But unfortunaly we can't tell what fixed ist.

**Closed** 2017-09-02 08:53 UTC
